import = [
   "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[window]
opacity = 0.75
blur = true
startup_mode = "Windowed"

[env]
TERM = "xterm-256color"

[scrolling]
history = 20000

[font]
size = 15

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"
